#!/bin/sh
powershell="c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -command post-commit.ps1"

exec $powershell

#root_dir=`git rev-parse --show-toplevel`
#link="$root_dir/.git/rr-cache"
#link_resolver=`cd $link; pwd -P `
#rr_repo_root_dir=`dirname $link_resolver`
#
#commit_hash=`git log -1 --pretty=%H --branches integration`
#commit_repo=`git remote -v | grep '.*(push)$' | awk '{ print $2 }' | sed -e "s/^.*\///" -e "s/.git//"`
#commit_string="rerere cache of commit $commit_hash of integration branch of repository $commit_repo"
#
#git -C $rr_repo_root_dir add .
#if git -C $rr_repo_root_dir commit -m "$commit_string"
#then 
#	echo "Successfully commited rr-cache"
#else 
#	echo "Error while commit"
#	exit 1
#fi
#if git -C $rr_repo_root_dir push origin master
#then
#	echo "Successfully pushed rr-cache"
#else
#	echo "Error while pushing"
#	exit 1
#fi
#